// <auto-generated />
using System;
using InmobiliariaMinimalAPI.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobiliariaMinimalAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402120839_CorreccionDatosSemilla")]
    partial class CorreccionDatosSemilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InmobiliariaMinimalAPI.Modelos.Propiedad", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropiedad");

                    b.ToTable("Propiedad");

                    b.HasData(
                        new
                        {
                            IdPropiedad = 1,
                            Activa = true,
                            Descripcion = "Una hermosa casa ubicada en el centro de la ciudad.",
                            FechaCreacion = new DateTime(2026, 4, 2, 13, 50, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Casa en el centro",
                            Ubicacion = "Calle Principal 123"
                        },
                        new
                        {
                            IdPropiedad = 2,
                            Activa = true,
                            Descripcion = "Un moderno apartamento con una vista espectacular al mar.",
                            FechaCreacion = new DateTime(2026, 4, 2, 13, 50, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Apartamento con vista al mar",
                            Ubicacion = "Avenida del Mar 456"
                        },
                        new
                        {
                            IdPropiedad = 3,
                            Activa = false,
                            Descripcion = "Una encantadora casa de campo rodeada de naturaleza.",
                            FechaCreacion = new DateTime(2026, 4, 2, 13, 50, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Casa de campo",
                            Ubicacion = "Camino Rural 789"
                        },
                        new
                        {
                            IdPropiedad = 4,
                            Activa = true,
                            Descripcion = "Un piso moderno ubicado en una zona residencial tranquila.",
                            FechaCreacion = new DateTime(2026, 4, 2, 13, 50, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Piso en zona residencial",
                            Ubicacion = "Barrio Residencial 321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
